M48
; DRILL file {KiCad (6.0.0)} date Tue Aug 16 21:02:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-16T21:02:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1102
%
G90
G05
T1
X3.62Y-3.385
X4.58Y-3.385
X4.58Y-4.345
X5.0Y-3.275
X5.0Y-4.425
X7.0Y-3.275
X7.0Y-4.425
X7.42Y-3.355
X7.42Y-4.315
X8.38Y-3.355
X8.38Y-4.315
T2
X3.62Y-4.345
T3
X5.973Y-4.559
T0
M30
